version: '3'
services:
  nginx:
    build: ./nginx
    container_name: nginx
    links:
      - consul
    ports:
      - "80:80"
    labels:
      SERVICE_IGNORE: 'yes'
  consul:
    container_name: consul-nasterblue
    image: consul
    ports:
      - "8500:8500"
      - "8600:8600"
    command: "agent -enable-script-checks -server -ui -node=nasterblue-server -bootstrap-expect=1 -client=0.0.0.0"


  registrator:
    command: "-internal consul://consul:8500"
    image: gliderlabs/registrator:latest
    container_name: registrator
    links:
      - consul
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"

  beesightsoft-alpine-hello-world:
    image: beesightsoft/alpine-hello-world:latest
    labels:
      SERVICE_80_NAME: beesightsoft-alpine-hello-world
      SERVICE_80_CHECK_HTTP: /
      SERVICE_80_CHECK_INTERVAL: 5s
      SERVICE_443_IGNORE: 'yes'
      SERVICE_TAGS: production
    ports:
      - "80"
