version: "3"
services:
  rabbitmq:
    image: rabbitmq:3
    ports:
      - 127.0.0.1:5672:5672
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  nginx:
    image: nginx
    ports:
      - 127.0.0.1:80:80

  redis:
    image: redis
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - redis:/data

  consul:
    container_name: consul-nasterblue
    image: consul
    ports:
      - 127.0.0.1:8500:8500
      - 127.0.0.1:8600:8600
    volumes:
      - /Volumes/DATA/resources/pilot/consul/consul.d/:/consul/config
    command: "agent -server -ui -node=nasterblue-server -bootstrap-expect=1 -client=0.0.0.0"

volumes:
  rabbitmq:
  redis: